config/routes.rb
Igbo::Application.routes.draw do
  resources :english_entries

  root :to => 'home#dictionary'
  match 'dictionary' => 'home#dictionary'
end

app/models/english_entry.rb
class EnglishEntry < ActiveRecord::Base
end

app/models/igbo_entry.rb
class IgboEntry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_variables
  
  def set_variables
    @igbo_count     = IgboEntry.count
    @english_count  = EnglishEntry.count
  end
end

app/controllers/english_entries_controller.rb
class EnglishEntriesController < ApplicationController
  # GET /english_entries
  # GET /english_entries.json
  def index
    @english_entries = EnglishEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @english_entries }
    end
  end

  # GET /english_entries/1
  # GET /english_entries/1.json
  def show
    @english_entry = EnglishEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @english_entry }
    end
  end

  # GET /english_entries/new
  # GET /english_entries/new.json
  def new
    @english_entry = EnglishEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @english_entry }
    end
  end

  # GET /english_entries/1/edit
  def edit
    @english_entry = EnglishEntry.find(params[:id])
  end

  # POST /english_entries
  # POST /english_entries.json
  def create
    @english_entry = EnglishEntry.new(params[:english_entry])

    respond_to do |format|
      if @english_entry.save
        format.html { redirect_to @english_entry, notice: 'English entry was successfully created.' }
        format.json { render json: @english_entry, status: :created, location: @english_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @english_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /english_entries/1
  # PUT /english_entries/1.json
  def update
    @english_entry = EnglishEntry.find(params[:id])

    respond_to do |format|
      if @english_entry.update_attributes(params[:english_entry])
        format.html { redirect_to @english_entry, notice: 'English entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @english_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /english_entries/1
  # DELETE /english_entries/1.json
  def destroy
    @english_entry = EnglishEntry.find(params[:id])
    @english_entry.destroy

    respond_to do |format|
      format.html { redirect_to english_entries_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dictionary
    @q        = params[:q]
    @dict     = params[:dict]
    
    if @q
      klass     = params[:dict] == 'ig-en' ? IgboEntry : EnglishEntry
      @results  = klass.where('term LIKE ?', "#{@q}%").paginate(:page => params[:page], :per_page => 20)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/english_entries_helper.rb
module EnglishEntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/english_entries/_form.html.haml
= form_for @english_entry do |f|
  -if @english_entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@english_entry.errors.count, "error")} prohibited this english_entry from being saved:"
      %ul
        - @english_entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :language
    = f.text_field :language
  .field
    = f.label :term
    = f.text_field :term
  .field
    = f.label :term_class
    = f.text_field :term_class
  .field
    = f.label :definition
    = f.text_area :definition
  .actions
    = f.submit 'Save'

app/views/english_entries/edit.html.haml
%h1 Editing english_entry

= render 'form'

= link_to 'Show', @english_entry
\|
= link_to 'Back', english_entries_path

app/views/english_entries/index.html.haml
%h1 Listing english_entries

%table
  %tr
    %th Language
    %th Term
    %th Term class
    %th Definition
    %th
    %th
    %th

  - @english_entries.each do |english_entry|
    %tr
      %td= english_entry.language
      %td= english_entry.term
      %td= english_entry.term_class
      %td= english_entry.definition
      %td= link_to 'Show', english_entry
      %td= link_to 'Edit', edit_english_entry_path(english_entry)
      %td= link_to 'Destroy', english_entry, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New English entry', new_english_entry_path

app/views/english_entries/new.html.haml
%h1 New english_entry

= render 'form'

= link_to 'Back', english_entries_path

app/views/english_entries/show.html.haml
%p#notice= notice

%p
  %b Language:
  = @english_entry.language
%p
  %b Term:
  = @english_entry.term
%p
  %b Term class:
  = @english_entry.term_class
%p
  %b Definition:
  = @english_entry.definition

= link_to 'Edit', edit_english_entry_path(@english_entry)
\|
= link_to 'Back', english_entries_path

app/views/home/_en-ig.html.haml
%h2 Results
%p= "Search term: #{@q}"
%p= @results

app/views/home/_ig-en.html.haml
%h2 Results
%p= "Search term: #{@q}"

- @results.each do |result|
  %p= result.definition

= will_paginate @results

app/views/home/dictionary.html.haml
.content
  %header
    %h1= link_to "Mkpuruokwu Igbo:", "/"
    %h2 The Igbo Dictionary
    %p
      By
      = link_to "Oge Nnadi", "http://oge.nnadi.org"
      
  .search
    = form_tag '/dictionary', :method => :get do
      = text_field_tag :q, @q, :size => 30
      = select_tag(:dict, options_for_select([["Igbo -> English", "ig-en"], ["English -> Igbo", "en-ig"]], @dict))
      %button Search

  .instructions
    %table
      %thead
        %tr
          %td Use
          %td Instead of
      
      %tbody
        %tr
          %td c
          %td ch
        %tr
          %td ë
          %td ẹ
        %tr
          %td ï
          %td ị
        %tr
          %td ö
          %td ọ
        %tr
          %td ü
          %td ụ
        
  .results
    - if @q
      - if !@results.empty?
        %h2 Results
        %p= "Search term: #{@q}"

        - @results.each do |result|
          .result
            .term= result.term.force_encoding("UTF-8") if result.term
            .term_class= result.term_class.force_encoding("UTF-8") if result.term_class
            .tones= "[#{result.tones.force_encoding("UTF-8")}]" if  @dict == "ig-en" && result.tones
            .definition= result.definition.force_encoding("UTF-8") if result.definition

        = will_paginate @results
      - else
        %p No results found

      
  %footer
    %p
      This dictionary contains #{number_with_delimiter(@english_count)} English and #{number_with_delimiter(@igbo_count)} Igbo entries.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mkpuruokwu Igbo: A large online Igbo dictionary
    %meta{:content => "Mkpuruokwu Igbo is an online Igbo dictionary containing #{number_with_delimiter(@english_count)} English and #{number_with_delimiter(@igbo_count)} Igbo entries.", :property => "description"}
    %link{:href=>"home.css", :rel=>"stylesheet", :type=>'text/css'}
    = csrf_meta_tags
  
%body
  = yield
  :javascript
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-25743661-1']);
    _gaq.push(['_setDomainName', 'mkpuruokwu.org']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();